#!/bin/bash

# This script assumes that postgresql is downloaded on the machine
# and there is a postgres role named 'myprojectuser' with CREATE priveleges.

psql <<EOF
CREATE USER myprojectuser WITH PASSWORD 'password' CREATEDB;
DROP DATABASE IF EXISTS spectrodb;
CREATE DATABASE spectrodb OWNER myprojectuser;
EOF

psql spectrodb myprojectuser <<EOF
CREATE SCHEMA minerals;
CREATE TABLE samples (
ID CHAR(15),
DATA_ID CHAR(10) PRIMARY KEY NOT NULL,
SAMPLE_ID VARCHAR(20) NOT NULL,
DATE_ACCESSED TIMESTAMP,
ORIGIN VARCHAR(50),
LOCALITY VARCHAR(50),
NAME VARCHAR(25) NOT NULL,
SAMPLE_DESC VARCHAR(100),
SAMPLE_TYPE VARCHAR(25),
SAMPLE_CLASS VARCHAR(25),
SUB_CLASS VARCHAR(25),
GRAIN_SIZE VARCHAR(25),
VIEW_GEOM float ARRAY[4],
RESOLUTION float ARRAY[4],
REFL_RANGE float ARRAY[2],
FORMULA VARCHAR(20),
COMPOSITION VARCHAR(100),
REFLECTANCE JSON
);
EOF
