#!/bin/bash

# This script assumes that postgresql is downloaded on the machine
# and there is a postgres role named 'myprojectuser' with CREATE priveleges.

psql spectrodb myprojectuser <<EOF
CREATE SCHEMA minerals;
CREATE TABLE mars_sample (
DATA_ID CHAR(20) PRIMARY KEY NOT NULL,
SAMPLE_ID VARCHAR(30),
DATE_ADDED TIMESTAMP,
ORIGIN VARCHAR(100),
LOCALITY VARCHAR(100),
NAME VARCHAR(100) NOT NULL,
SAMPLE_DESC VARCHAR(500),
SAMPLE_TYPE VARCHAR(50),
SAMPLE_CLASS VARCHAR(50),
SUB_CLASS VARCHAR(50),
GRAIN_SIZE VARCHAR(50),
VIEW_GEOM VARCHAR(50),
RESOLUTION VARCHAR(30),
REFL_RANGE float ARRAY[2],
FORMULA VARCHAR(50),
COMPOSITION VARCHAR(1000),
REFLECTANCE JSON
);
EOF
