# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 07:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=15, unique=True)),
                ('sample_id', models.CharField(max_length=20)),
                ('date_accessed', models.DateTimeField()),
                ('origin', models.CharField(max_length=50)),
                ('locality', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sample_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_class', models.CharField(blank=True, max_length=50, null=True)),
                ('grain_size', models.CharField(blank=True, max_length=100, null=True)),
                ('view_geom', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('refl_range', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('formula', models.CharField(blank=True, max_length=20, null=True)),
                ('composition', models.CharField(blank=True, max_length=1000, null=True)),
                ('reflectance', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
