# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('data_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sample_id', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(max_length=100)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sample_desc', models.TextField(blank=True, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_class', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_class', models.CharField(blank=True, max_length=50, null=True)),
                ('grain_size', models.CharField(blank=True, max_length=50, null=True)),
                ('view_geom', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=30, null=True)),
                ('refl_range', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('formula', models.CharField(blank=True, max_length=50, null=True)),
                ('composition', models.CharField(blank=True, max_length=1000, null=True)),
                ('reflectance', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
