# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0002_auto_20170116_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mars.SampleType'),
        ),
    ]
