# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0003_auto_20170116_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampletype',
            old_name='type',
            new_name='typeOfSample',
        ),
    ]
