# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0005_auto_20170116_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'About Entry',
                'verbose_name_plural': 'About Entries',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['position', 'name'],
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sub_class',
        ),
    ]
