# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0007_auto_20170207_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'About Entry',
                'verbose_name_plural': 'About Entries',
            },
        ),
    ]
