# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0009_auto_20170207_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
