# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0010_teammember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
