# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0012_merge_20170627_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
