# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0014_sample_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sub_class',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'pic_folder/'),
        ),
    ]
